services:
  frontend:
    image: cjbates02/personal_website_frontend:latest 
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    image: cjbates02/personal_website_backend:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
