services:
  frontend:
    image: cjbates02/personal_website_frontend:latest 
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
  
  backend:
    image: cjbates02/personal_website_backend:latest
    environment:
      - FROM_EMAIL=${FROM_EMAIL}
      - TO_EMAIL=${TO_EMAIL}
      - TO_EMAIL_BACKUP=${TO_EMAIL_BACKUP}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
